name: Continuous integration checks

on:
    pull_request:
        branches: [master, develop]
    push:
        branches: [master]

jobs:
    lint:
        name: File linting on Node v${{ matrix.node }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node: [12, 14, 15.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set Node.js version
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node }}

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                path: node_modules
                key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.OS }}-build-${{ env.cache-name }}-
                  ${{ runner.OS }}-build-
                  ${{ runner.OS }}-

            - name: Install node packages
              run: npm install

            - name: Run linters
              run: npm run lint

    tests:
        name: Jest - Unit tests
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: false
            matrix:
                node: [12, 14, 15.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set Node.js version
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node }}

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                path: node_modules
                key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.OS }}-build-${{ env.cache-name }}-
                  ${{ runner.OS }}-build-
                  ${{ runner.OS }}-

            - name: Install node packages
              run: npm install

            - name: Run unit tests
              run: npm run testUnit
